reload guni

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,5 +1,18 @@
 #!/usr/bin/env bash
 # Get the PID of the master Gunicorn process
-master_pid=$(pgrep -f "gunicorn.*--workers")
-# Gracefully restart Gunicorn
-kill -s TERM "$master_pid"
+
+GUNICORN_PID=$(pgrep -f "/venv/bin/gunicorn.*api.v1.app:app")
+
+if [ -z "$GUNICORN_PID" ]; then
+    echo "Gunicorn process not found."
+    exit 1
+fi
+
+
+echo "Sending HUP signal to Gunicorn master process..."
+kill -HUP $GUNICORN_PID
+
+
+sleep 5  # Adjust this time based on your application's request processing time
+
+echo "Reloading Gunicorn completed."
